// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3XMqtYD9G8LuueAHqRWZJ1ooFN6meBrU',
    appId: '1:647911492340:web:30f8edc6f1cd0585a5eca1',
    messagingSenderId: '647911492340',
    projectId: 'farmer-brand',
    authDomain: 'farmer-brand.firebaseapp.com',
    storageBucket: 'farmer-brand.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYwFVTkftPEooaG2GUbSRI0w1A44mQ4Ss',
    appId: '1:647911492340:android:3baceb542231436aa5eca1',
    messagingSenderId: '647911492340',
    projectId: 'farmer-brand',
    storageBucket: 'farmer-brand.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAUdUv7jLh3KLYo-g-07bjZt4dSyyGiLw',
    appId: '1:647911492340:ios:361b44edabac662aa5eca1',
    messagingSenderId: '647911492340',
    projectId: 'farmer-brand',
    storageBucket: 'farmer-brand.firebasestorage.app',
    iosBundleId: 'com.brand.farmerBrand',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAUdUv7jLh3KLYo-g-07bjZt4dSyyGiLw',
    appId: '1:647911492340:ios:361b44edabac662aa5eca1',
    messagingSenderId: '647911492340',
    projectId: 'farmer-brand',
    storageBucket: 'farmer-brand.firebasestorage.app',
    iosBundleId: 'com.brand.farmerBrand',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3XMqtYD9G8LuueAHqRWZJ1ooFN6meBrU',
    appId: '1:647911492340:web:81ec5286d715693ca5eca1',
    messagingSenderId: '647911492340',
    projectId: 'farmer-brand',
    authDomain: 'farmer-brand.firebaseapp.com',
    storageBucket: 'farmer-brand.firebasestorage.app',
  );
}
