name: "Build & Release"

on:
  push:
    tags:
      - 'v*.*.*'  # Run only when pushing tags like v1.0.0

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - name: Get dependencies & build APKs
        run: |
          flutter clean
          flutter pub get
          flutter build apk --release --split-per-abi

      - name: Build IPA
        run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r app.ipa Payload
          mv app.ipa ../

      - name: List files
        run: ls -R build/

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/app/outputs/apk/release/*.apk
            build/ios/iphoneos/app.ipa
          tag: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ github.ref_name }}
